### ISSUE TITLE
Remove Dependency on Redis

### ISSUE THREAD

**Issue by nodanaonlyzuul** [NYPL-discovery/patron-service#1]
This application uses Redis to cache the OAuth token it gets from our sierra (who is the provider).
That may be overkill. We can experiment with just storing it in memory or on disk.

**Comment by kfriedman** [comment]
I removed the Redis dependency.

Because we no longer need Redis, I no longer need to run this lambda in a VPC. 😄

**Comment by nodanaonlyzuul** [comment]
How weird!
I didn't realize you can deploy lambdas in no VPC.
Man - they're really trying to hide the server from you.

**Comment by kfriedman** [comment]
Actually, best practice (http://docs.aws.amazon.com/lambda/latest/dg/best-practices.html) is to *not* install in a VPC. As per AWS: `Don't put your Lambda function in a VPC unless you have to. `.

There's overhead in installing it in an VPC as it needs to get an IP address, etc.
